### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by flaviogf** [flaviogf/promissory_note#10]
# Requirements
- [x] Specific implementation
- [x] Implement
---

# Implementation

## Use Cases

- [x] IssuePromissoryNote
  - [x] execute

## Commands

- [x] IssuePromissoryNoteCommand
  - [x] +number
    - [x] is greater than zero
  - [x] +due date
    - [x] is greater or equal today
  - [x] +value
    - [x] is greater than zero
  - [x] +beneficiary name
    - [x] is not none or whitespace
  - [x] +beneficiary cpf
    - [x] has len eleven
  - [x] +beneficiary email
    - [x] is email
  - [x] +currency
    - [x] is not none or whitespace
  - [x] +city payment
    - [x] is not none or whitespace
  - [x] +state payment
    - [x] is not none or whitespace
  - [x] +emitter name
    - [x] is not none or whitespace
  - [x] +emitter cpf
    - [x] has len eleven
  - [x] +emitter address
    - [x] is not none or whitespace
  - [x] +emitter email
    - [x] is email
  - [x] +issuance date
    - [x] is greater or equal today

## Entities

- [x] Beneficiary
  - [x] +name
  - [x] +cpf
  - [x] +email

- [x] Emitter
  - [x] +name
  - [x] +cpf
  - [x] +address
  - [x] +email

- [x] Promissory Note
  - [x] -number
  - [x] -due_date
  - [x] -value
  - [x] -currency
  - [x] -city_payment
  - [x] -state_payment
  - [x] -issuance_date
  - [x] -beneficiary
  - [x] -emmiter
  - [x] -subscribers
  - [x] +issue()
  - [x] +attach()

## Value objects
- [x] Name
  - [x] -name
- [x] Cpf
  - [x] -cpf
- [x] Email
  - [x] -email

## Events

- [x] PromissoryNoteIssued
  - [x] +number
  - [x] +due date
  - [x] +value
  - [x] +beneficiary name
  - [x] +beneficiary cpf
  - [x] +beneficiary email
  - [x] +currency
  - [x] +city payment
  - [x] +state payment
  - [x] +emitter name
  - [x] +emitter cpf
  - [x] +emitter address
  - [x] +emitter email
  - [x] +issuance date
  - [x] +notifications

- [x] PromissoryNoteNotIssued
  - [x] +notifications

### Services

- [x] PillowImageGenerationService
  - [x] +call()
  - [x] +generate()

- [x] SendGridEmailPromissoryNoteIssued
  - [x] +call()
  - [x] +send_promissory_note_issued()

### Cli
- [x] Cli

### Web
- [x] Web
